version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DATABASE=eventsocket
      - POSTGRES_USER=eventsocket
      - POSTGRES_PASSWORD=eventsocket
    ports:
      - "15432:5432"
  api:
    build: _infra/dev
    volumes:
      - .:/srv:rw
    depends_on:
      - db
    ports:
      - "4000:4000"
    working_dir: /srv
    command: mix phx.server
