version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DATABASE=eventsocket
      - POSTGRES_USER=eventsocket
      - POSTGRES_PASSWORD=eventsocket
    ports:
      - "15432:5432"
