name: API CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "web/**"

env:
  IMAGE_NAME: eventsocket-api

jobs:
  deploy-prod:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: API Production
      url: "https://api.eventsocket.brendonovich.dev"
    steps:
      - name: Pull
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -t $IMAGE_NAME

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        id: push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          echo "::set-output name=image-digest::$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_ID:$VERSION)"

      - name: Setup SSH
        run: |
          echo "Setting up SSH Key"

          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh

          ssh_port=22
          ssh_host=${{ secrets.DOKKU_REMOTE_URL }}

          echo "Generating SSH_HOST_KEY from ssh-keyscan against $ssh_host:$ssh_port"
          ssh-keyscan -H -p "$ssh_port" "$ssh_host" >> ~/.ssh/known_hosts

          echo "Adding SSH Key to ssh-agent"
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy
        run: ssh dokku@${{ secrets.DOKKU_REMOTE_URL }} git:from-image ${{ secrets.DOKKU_APP_NAME }} ghcr.io/brendonovich/eventsocket-api:latest
